# Adopt version 2 syntax:
#   https://docs.docker.com/compose/compose-file/#/versioning
version: '2'

volumes:
    database_data:
        driver: local

services:
    postgres:
        build: ./docker/postgres
        ports:
            - 5432:5432
        expose:
            - 5432
        restart: always
        environment:
            POSTGRES_USER: "sidewalk"
            POSTGRES_PASSWORD: "sidewalk"
            POSTGRES_DB: "sidewalk"
    web:
        build: ./docker/web
        ports:
            - 9000:9000
            - 9999:9999
        expose:
            - 9000
        environment:
            DATABASE_URL: jdbc:postgresql://postgres:5432/sidewalk
        stdin_open: true
        volumes:
            - ./SidewalkWebpage:/home/app
    grunt:
        build: ./docker/grunt
        volumes_from:
            - web
